name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    name: My Job
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Build-app
        run: chmod +x ci/build-app.sh && ci/build-app.sh